In [1]:
#Create an array from a list or tuple
#np.array   
import numpy as np 
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
#np.zeros
#Create an array of zero of specified shape
import numpy as np
arr= np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#np.ones
#create an array of ones with specified shape
import numpy as np
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#np.arange 
#Generate the range of numbers 
import numpy as np 
arr=np.arange(1,30 , 3)
print(arr)

[ 1  4  7 10 13 16 19 22 25 28]


In [8]:
#np.linspace
#Generate an array of evenly spaced numbers over a speceified interval
import numpy as np 
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
#np.reshape 
#Reshape an array 
import numpy as np
arr=np.arange(9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#np.transpose
#Transpose an array 
import numpy as np
arr= np.array([[1,2,3] , [9,8,7]])
arr=np.transpose(arr)
print(arr)

[[1 9]
 [2 8]
 [3 7]]


In [14]:
#np.dot
#compute dot product of array
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dot(arr1,arr2)
print(arr)

32


In [15]:
#50 logarithmic array 
import numpy as np
arr=np.logspace(1,5,50)
print(arr)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


In [17]:
#np.eye
#Identity matrix with 1 in diagonal and rest 0 are elements 
import numpy as np


identity_3x3 = np.eye(3)
print(identity_3x3)


identity_3x5 = np.eye(3, 5)
print(identity_3x5)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [21]:
#np.diag
#Extract diagonal of array or make diagonal array 
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
diag=np.diag(arr)

print(diag)


[1 5 9]


In [23]:
#np.random.rand 
#Random number of 4corss 3 martrix
import numpy as np
arr=np.random.rand(3,4)
print(arr)



[[0.6624418  0.92666864 0.23365639 0.80157788]
 [0.20766344 0.16182164 0.68419904 0.02588208]
 [0.59748717 0.99767551 0.88271728 0.13298123]]


In [25]:
#Basic statistics
arr= np.array([1,2,3,4,5])
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))


1
5
15
3.0
1.4142135623730951


In [27]:
#np.arangmin,argmax
#indices of an array which gives maximum and minimum values 
arr=np.array([1,2,3,4,5,6])
print("np.argmin" , np.argmin(arr))

np.argmin 0


In [29]:
print("np.argmax" , np.argmax(arr))

np.argmax 5


In [32]:
#Concatenate arrays along a specified axis
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr_concat = np.concatenate((arr1, arr2), axis=0)
print("np.concatenate along axis 0:")
print(arr_concat)

np.concatenate along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#Concatenate arrays along a specified axis
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr_concat = np.concatenate((arr1, arr2), axis=1)
print("np.concatenate along axis 0:")
print(arr_concat)

np.concatenate along axis 0:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
